  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.16
        with:
          cuda: '12.1.0'

      - name: Configure and Build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_CUDA_ARCHITECTURES="all"
          make -j$(nproc)

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VCORE_v144_Engine_Linux
          path: build/vcore_engine
