      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.16
        with:
          cuda: '12.1.0'
          method: 'network'

      # ДОБАВЬ ЭТОТ ШАГ: Настройка окружения Visual Studio
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        # Добавляем флаг, чтобы CMake точно нашел CUDA
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_CUDA_COMPILER="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1/bin/nvcc.exe"
